name: "Copy File with NodeJS Copy"
description: "Copies a file using nodejs"
labels: copy nodejs cross-platform file
branding:
  icon: file
  color: purple
inputs:
  source: # id of input
    description: "Source File"
    required: true
    default: ""
  target: # id of input
    description: "Target File"
    required: true
    default: ""
  cwd: # id of input
    description: "WorkDir"
    required: false
    default: ""
  srcBase: # id of input
    description: "Source File Base dir"
    required: false
    default: ""
  destBase: # id of input
    description: "Target File Base dir"
    required: false
    default: ""
  modeOne: # id of input
    description: "one file copy mode"
    required: false
    default: ""
  modeMulti: # id of input
    description: "multi line source mode"
    required: false
    default: ""
runs:
  using: "node16"
  main: "index.js"
