name: "Copy File with NodeJS"
description: "Copies a file using nodejs"
inputs:
  source: # id of input
    description: "Source File"
    required: true
    default: ""
  target: # id of input
    description: "Target File"
    required: true
    default: ""
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  steps:
    - run: yarn      
    - run: node
        using: "node16"
        pre: yarn
        main: "index.js"
