name: "Copy File with NodeJS"
description: "Copies a file using nodejs"
labels: copy nodejs cross-platform file
icon: file
color: purple
inputs:
  source: # id of input
    description: "Source File"
    required: true
    default: ""
  target: # id of input
    description: "Target File"
    required: true
    default: ""
runs:
  using: "node16"
  main: "index.js"
