name: copy files
on: [ push, workflow_dispatch ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy file
        uses: Lyoko-Jeremie/js-copy-github-action@master
        with:
          source: ./*.yml
          target: /tmp/
